#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.137                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: src_advancedimagesearchlib_advancedimagesearchlib src_lsimg_lsimg

src_advancedimagesearchlib_advancedimagesearchlib: 
	$(MAKE) -C src/AdvancedImageSearchLib all -f AdvancedImageSearchLib.cbp.mak

src_lsimg_lsimg: 
	$(MAKE) -C src/lsimg all -f lsimg.cbp.mak

clean: clean_src_advancedimagesearchlib_advancedimagesearchlib clean_src_lsimg_lsimg

clean_src_advancedimagesearchlib_advancedimagesearchlib: 
	$(MAKE) -C src/AdvancedImageSearchLib clean -f AdvancedImageSearchLib.cbp.mak

clean_src_lsimg_lsimg: 
	$(MAKE) -C src/lsimg clean -f lsimg.cbp.mak

.PHONY: clean_src_advancedimagesearchlib_advancedimagesearchlib clean_src_lsimg_lsimg

