#ifndef CONFIGURATION_H_INCLUDED
#define CONFIGURATION_H_INCLUDED


#define USE_OPENCV_FACEDETECTION 0
#define USE_PATTERN_RECOGNITION 0

#define USE_PNG_FILES 0
#define USE_JPG_FILES 1


#define USE_TIMERS 1


#endif // CONFIGURATION_H_INCLUDED
