#ifndef CONFIGURATION_H_INCLUDED
#define CONFIGURATION_H_INCLUDED


//#define USE_OPENCV_FACEDETECTION 0
//#define USE_PATTERN_RECOGNITION 0

#define USE_TIMERS 1

#define USE_CACHING 1

#define PRINT_DEBUG_INFO 0


extern int visualization;
#endif // CONFIGURATION_H_INCLUDED
